###
GET http://localhost:9000/api/empleados HTTP/1.1

####


PUT http://localhost:9000/api/empleados/1032357785 HTTP/1.1
Content-Type: application/json

{"nombres":"Daniel","apellidos":"Acuña","fecha_nacimiento":"1985-11-24","correo_electronico":"hola@gmail.com","celularualizar":"22222222222222","direccion":"Cra 4 30c 120","departamento":"Cundinamarca","ciudad":"Soacha","profesion":"Desarrollador de software","rol_idualizar":"1","contrasena":"987654"}
